# NOTE: unused and incomplete
# This is what I thought the YAML config would look like - it's a bit of a nightmare.
attack:
  Aggregated:
    Dribble: 
      features: ["normalised_location_count", "normalised_count", "count"]
    Shot:
      types: ["Open Play", "Corner"]
      features: ["normalised_location_count", "normalised_count", "shot_aerial_won_ratio", "shot_first_time_ratio"]
    Pass:
      types: [Null, "Intercept"]
      features: [
        "normalised_location_count",
        "normalised_count",
        "count",
        "direction_forward_ratio", # percentage of passes forward
        "direction_backward_ratio", # percentage of passes backward
        "direction_sideways_ratio", # percentage of passes sideways
        "distance_short_ratio", # what percentage of passes are short
        "distance_medium_ratio", # medium
        "distance_long_ratio", # long
        "success_rate",
        "high_pass_ratio", 
        "cross_ratio" # percentage of passes that are crosses
      ]
  Non-aggregated:
    - "tactics"  # most common tactic

defense:
  # - Ball Recovery
  - Duel:
    features:
      - count
      - normalised_count
      - normalised_location_count
  - Ball Recovery:
    - features:
      - count
      - normalised_count
      - normalised_location_count
  - Pressure:
    - features:
      - count
      - normalised_count
      - normalised_location_count
  - Foul Committed:
    - features:
      - count
      - normalised_count
      - normalised_location_count
  - Clearance:
    - features:
      - count
      - normalised_count
      - normalised_location_count