# count: sum of events in game
# location_count: sum of events in an area of the pitch
# norm_count: count of events / total number of events
# direction_count: count of events in direction (forward, backwards, sideways)
# distance_count: count of events that are short, medium, long
# success_average: average success rate
# aerial_count: number of events in the air
# norm_aerial_count: average

# normalised locations of ... means number of events taken in an area / total number of events
# Aim is to tell us relatively where the events are done

# Columns which are derived from event information
# Columns which are derived from event types

# In the python code we can read a list of feature names from a yaml and process accordingly.


  # These features can be derived by groupby the "Type" column and aggregating
attack:
  Aggregated:
    Dribble: 
      features: ["normalised_location_count", "normalised_count", "count"]
    Shot:
      types: ["Open Play", "Corner"]
      features: ["normalised_location_count", "normalised_count", "shot_aerial_won_ratio", "shot_first_time_ratio"]
    Pass:
      types: [Null, "Intercept"]
      features: [
        "normalised_location_count",
        "normalised_count",
        "count",
        "direction_forward_ratio", # percentage of passes forward
        "direction_backward_ratio", # percentage of passes backward
        "direction_sideways_ratio", # percentage of passes sideways
        "distance_short_ratio", # what percentage of passes are short
        "distance_medium_ratio", # medium
        "distance_long_ratio", # long
        "success_rate",
        "high_pass_ratio", 
        "cross_ratio" # percentage of passes that are crosses
      ]
  Non-aggregated:
    - "tactics"  # most common tactic

defense:
  # - Ball Recovery
  - Duel:
    features:
      - count
      - normalised_count
      - normalised_location_count
  - Ball Recovery:
    - features:
      - count
      - normalised_count
      - normalised_location_count
  - Pressure:
    - features:
      - count
      - normalised_count
      - normalised_location_count
  - Foul Committed:
    - features:
      - count
      - normalised_count
      - normalised_location_count
  - Clearance:
    - features:
      - count
      - normalised_count
      - normalised_location_count